name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el código del repo
      - name: Descargar código del repo
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # 4️⃣ Verificar archivos y rutas
      - name: Verificar estructura de archivos
        run: |
          echo "Contenido de la raíz del proyecto:"
          ls -la
          echo "Contenido de la carpeta tests:"
          ls -la tests

      # 5️⃣ Ejecutar pruebas
      - name: Ejecutar pruebas
        run: npm test
